name: Validation

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and Test on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macOS-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    defaults:
      run:
       shell: bash
    env:
      MAVEN_OPTS: -Xmx2048m
      MAVENPARAMS: --no-transfer-progress
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11.0.18'
        java-package: jdk
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven
    - name: Build & test core
      run: ./scripts/runcoretests.sh
    - name: Start P2 repository
      run: ./scripts/startp2.sh
    - name: Build & test application
      run: ./scripts/runapptests.sh
    - name: Build & test agent
      run: ./scripts/runagenttests.sh
    - name: Check formatting
      run: ./scripts/checkformatting.sh
